steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi

      - name: Create Output Dir
        shell: bash
        run: mkdir -p output

      # --- COMPILATION WINDOWS ---
      - name: Build All (Windows)
        if: runner.os == 'Windows'
        run: |
          gcc src/server.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/nyxj-windows-x64.exe -lws2_32
          gcc examples/api_example/api_example.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/example-api_example-windows-x64.exe -lws2_32
          gcc examples/client_test/client_test.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/example-client_test-windows-x64.exe -lws2_32

      # --- COMPILATION LINUX X64 ---
      - name: Build All (Linux x64)
        if: runner.os == 'Linux' && matrix.arch == 'x86_64'
        run: |
          gcc src/server.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/nyxj-linux-x64 -lpthread
          gcc examples/api_example/api_example.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/example-api_example-linux-x64 -lpthread
          gcc examples/client_test/client_test.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/example-client_test-linux-x64 -lpthread

      # --- COMPILATION LINUX ARM64 ---
      - name: Build All (Linux ARM64)
        if: runner.os == 'Linux' && matrix.arch == 'arm64'
        run: |
          aarch64-linux-gnu-gcc src/server.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/nyxj-linux-arm64 -lpthread
          aarch64-linux-gnu-gcc examples/api_example/api_example.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/example-api_example-linux-arm64 -lpthread
          aarch64-linux-gnu-gcc examples/client_test/client_test.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/example-client_test-linux-arm64 -lpthread

      # --- COMPILATION MACOS ---
      - name: Build All (macOS)
        if: runner.os == 'macOS'
        run: |
          gcc src/server.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/nyxj-macos-arm64
          gcc examples/api_example/api_example.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/example-api_example-macos-arm64
          gcc examples/client_test/client_test.c src/core/parser.c vendor/mongoose/mongoose.c -Iinclude -Ivendor/mongoose -o output/example-client_test-macos-arm64

      # --- UPLOAD ---
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaires-${{ matrix.suffix }}
          path: output/*